### PR TITLE
Added chatgpt temperature environment variable

### PR DESCRIPTION
**Pull request by deetungsten**
Hello,

I looked through the API and noticed that you can set the temperature. I added an environment so you can set the temperature to another value besides the default (0.8)

### CODE REVIEW

**Comment by max298** [comment]
Thank you very much! I've noticed that the waylaidwanderer/node-chatgpt-api library doesn't [know much about the impact](https://github.com/waylaidwanderer/node-chatgpt-api/blob/0ab09f57b49a10904dcb3ddac4b24594fdb41b2a/README.md?plain=1#L506) of changing the temperature, should we add some sort of documentation for our users?

**Comment by deetungsten** [comment]
@max298, I think it's fairly known how the temperature effects the performance in a qualitative sense (here's a [medium](https://algowriting.medium.com/gpt-3-temperature-setting-101-41200ff0d0be) article with a decent explanation). Closer to 0 is more deterministic which is good for technical question. Closer to 1 and above makes it more random and "creative" which makes it better for content generation. The remark in the link you provided is that no one knows what ChatGPT temperature is set at by OpenAI but 0.8 (the default in node-chatgpt-api) is a decent guess, it fairly standard to be closer to 0.7 for precise answers.

**Comment by deetungsten** [comment]
@max298 I added some context to the README and `env.example`

**Comment by max298** [comment]
Thank you so much! I can't wait to play around with this 👍

**Review by max298 — APPROVED** [review]

**Pull request merged**
